spring.application.name=Text_Generation_By_AI
server.port=8085
groq.text.api.key=${DATASOURCE_GROQ_TEXT_API_KEY}

groq.image.api.key=${DATASOURCE_GROQ_IMAGE_API_KEY}

huggingface.api.url=${DATASOURCE_HUGGINGFACE_API_URL}

huggingface.api.key=${DATASOURCE_HUGGINGFACE_API_KEY}